### ISSUE TITLE
请问为什么运行这个程序的时候不需要管理员权限?

### ISSUE THREAD

**Issue by AnxysUaen** [wordpress219/steam-icon-fix#1]
请问为什么这个程序通过Python可以不弹管理员授权就能向C盘写入文件?试了一下,用本地的PowerShell都无法创建文件,有什么技巧吗

**Comment by brotherjie-win** [comment]
请问确定Steam安装在C盘受限目录Program Files或Program Files (x86)下吗，这两个必须提升权限才能写入，其他目录没有限制。
如果安装在其他盘下，即使是上面两个目录win11也不需要管理员权限。这和游戏是否安装在C盘并无关系，你可能是这里误解了。
Steam存储所有游戏图标的位置在安装目录下（一般根目录是Steam）的steam\games这个文件夹下，即使是安装在其他盘的游戏，其程序图标也都是保存在这个目录下面的，我这里没有发现例外情况。
换言之，只要Steam不是安装在C盘默认路径下，都不需要管理员权限。

**Comment by brotherjie-win** [comment]
Finished
