### ISSUE TITLE
输入steam安装目录后程序报错

### ISSUE THREAD

**Issue by GrandC1oud** [wordpress219/steam-icon-fix#3]
报错码:
WebAPI boostrap failed: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /ISteamDirectory/GetCMList/v1/?cellid=0&format=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
请问这种情况怎么解决

**Comment by brotherjie-win** [comment]
应该是你的网络不能直连Steam的API服务器，可以参考[中文教程](https://github.com/brotherjie-win/steam-icon-fix/blob/main/README_SC.md)里面的“代理服务器用户注意事项”这一节配置一下代理。
